"""
Filename: protocol.py
Author: Ondrej Patejdl
Contact: opatejdl@students.zcu.cz
Description: This script defines constants of the protocol
"""

from enum import Enum

PROTOCOL_HEADER = "OP23|"
SPLITTER = "|" 
MAX_BUFFER_SIZE = 1024
PROTOCOL_ENDING = "\n"
MIN_ARGS = 1
CMD_POS = 0

# AUTH
NUM_INDEX = 1

# LOGIN|<code>
LOGIN_ARGS = 2
CODE_POS = 1

LOGIN_SUCCESS = 0
LOGIN_RECONNECT = 1
LOGIN_FULL_SERVER = 2
LOGIN_NICK_DUPLICITY = 3
LOGIN_MAX_NICK_LEN = 4
LOGIN_MIN_NICK_LEN = 5

# GAME
GAME_ARGS = 2
GAME_START_ARGS = 4
GAME_RESUME_ARGS = 3
GAME_CODE = 1

GAME_START_SYM = 1
GAME_START_NICK = 2
GAME_START_BOARD = 3

GAME_RESUME_TURN: int = 2

# TURN
TURN_ARGS = 4
TURN_CODE = 1
TURN_BOARD = 2
TURN_NEXT = 3

TURN_VALID = "0"
TURN_NOT_YOUR = "1"
TURN_INVALID_MOVE = "2"
TURN_OCCUPIED_FILED = "3"
TURN_NOT_BELONG = "4"
TURN_NOT_RUN = "5"

# RESULT
RESULT_MIN_ARGS = 3

RESULT_WINNER_CODE = "0"

RESULT_RESULT = 1
RESULT_BOARD = 2
RESULT_WINNER = 3

# SYNC
SYNC_MIN_ARGS = 2
SYNC_GAME_ARGS = 6
SYNC_RESULT_ARGS = 5

SYNC_STATE = 1

SYNC_GAME_SYM = 2
SYNC_GAME_BOARD = 3
SYNC_GAME_TURN = 4
SYNC_GAME_OPPONENT = 5

SYNC_RESULT_OPPONENT = 2
SYNC_RESULT_BOARD = 3
SYNC_RESULT_WINNER = 4

# Client States
class ClientState(Enum):
    LOGIN = 0
    LOBBY = 1
    WAITING = 2
    IN_GAME = 3
    RESULT = 4
    SYNCING = 5